import { Button, EmptyState, Field, Input, NumberInput, Combobox, Select, cx } from '@flowhub/plugin-common/react';
import type { NetdataHistory, NetdataPanelProps } from './types';
import './styles.css';

function HistoryGraph({ history }: { history: NetdataHistory }) {
  const rows = history.data.filter((row) => Number.isFinite(row[0]));
  const values = rows.flatMap((row) => row.slice(1)).filter((value): value is number => Number.isFinite(value));
  if (!rows.length || !values.length) return <EmptyState size="compact" title="此范围没有历史数据" description="Agent 不会补造缺失样本。" />;
  const min = Math.min(0, ...values), max = Math.max(1, ...values), start = rows[0][0] as number, end = rows.at(-1)?.[0] as number;
  const colors = ['#a9e8bc', '#7baed7', '#efa85d', '#d995af'];
  return <div className="nd-chart"><svg viewBox="0 0 700 220" role="img" aria-label="Netdata 历史曲线">
    {history.labels.slice(1).map((label, index) => { let d = '', pen = false; rows.forEach((row) => { const value = row[index + 1]; if (!Number.isFinite(value)) { pen = false; return; } const x = 32 + (((row[0] as number) - start) / (end - start || 1)) * 646; const y = 186 - (((value as number) - min) / (max - min || 1)) * 160; d += `${pen ? 'L' : 'M'}${x.toFixed(1)},${y.toFixed(1)} `; pen = true; }); return <path key={label} d={d} stroke={colors[index % colors.length]} />; })}
    <text x="32" y="16">{max.toFixed(1)} {history.units ?? ''}</text><text x="32" y="210">{new Date(start * 1000).toLocaleString()}</text><text x="678" y="210" textAnchor="end">{new Date(end * 1000).toLocaleString()}</text>
  </svg><div className="nd-legend">{history.labels.slice(1).map((label, index) => <span key={label}><i style={{ background: colors[index % colors.length] }} />{label}</span>)}</div></div>;
}

export function NetdataPanel({ instances, charts, draft, historyQuery, history, installDraft, installHosts, installPreview, suggestion, state, busy = false, actions }: NetdataPanelProps) {
  const historyInstance = instances.find((item) => item.id === historyQuery.instanceId);
  const statusClass = `nd-status nd-status--${state.status}`;
  return <section className="nd-panel">
    <header className="nd-head"><div><span>MONITORING / AGENT</span><h3>Netdata</h3></div><p>每台机器连接自己的 Agent；历史保留在远端。</p></header>
    <div className="nd-layout"><div className="nd-main">
      <section className="nd-section"><div className="nd-title"><h4>已接入节点 <small>{instances.length}</small></h4></div>{instances.length ? <div className="nd-list">{instances.map((item) => <article key={item.id}><div><strong>{item.name}</strong><span>{item.url}</span></div><div><Button size="sm" variant="ghost" disabled={busy} onClick={() => actions.onEdit(item)}>编辑</Button><Button size="sm" variant="ghost" disabled={busy} onClick={() => actions.onHistoryChange('instanceId', item.id)}>历史</Button><Button size="sm" variant="danger" disabled={busy} onClick={() => actions.onRemove(item)}>移除</Button></div></article>)}</div> : <EmptyState size="compact" title="尚未接入 Netdata" description="可接入已有 Agent，或从右侧生成安装计划。" />}</section>
      <section className="nd-section"><div className="nd-title"><h4>接入已有 Agent</h4><small>HTTP / 19999</small></div>{suggestion ? <div className="nd-suggestion" role="status"><span>{suggestion.message}</span>{suggestion.url ? <Button size="sm" variant="ghost" onClick={actions.onUseSuggestion}>使用此地址</Button> : null}</div> : null}<div className="nd-grid"><Field label="节点名称" htmlFor="nd-name"><Input id="nd-name" value={draft.name} maxLength={40} disabled={busy} onChange={(event) => actions.onDraftChange('name', event.currentTarget.value)} /></Field><Field label="Agent 地址" htmlFor="nd-url"><Input id="nd-url" type="url" value={draft.url} disabled={busy} placeholder="http://机器IP:19999" onChange={(event) => actions.onDraftChange('url', event.currentTarget.value)} /></Field></div><Field label="网速指标" htmlFor="nd-network"><Combobox placeholder="搜索网卡指标" id="nd-network" value={draft.networkChart} disabled={busy} options={[{ value: 'system.net', label: '所有物理网卡 · system.net' }, ...charts.filter((item) => item.id.startsWith('net.')).map((item) => ({ value: item.id, label: item.id }))]} onChange={(value) => actions.onDraftChange('networkChart', value)} /></Field><div className="nd-actions"><Button variant="secondary" disabled={busy} onClick={actions.onTest}>测试并发现指标</Button><Button variant="primary" disabled={busy} onClick={actions.onSave}>保存节点</Button><Button variant="ghost" disabled={busy} onClick={actions.onReset}>重置</Button></div></section>
      <section className="nd-section"><div className="nd-title"><h4>历史趋势</h4><small>{historyInstance?.name ?? '选择节点'}</small></div>{historyInstance ? <><div className="nd-grid"><Field label="指标" htmlFor="nd-chart"><Combobox placeholder="搜索指标" id="nd-chart" value={historyQuery.chartId} disabled={busy} options={(charts.length ? charts : [{ id: 'system.cpu', units: '%' }]).map((item) => ({ value: item.id, label: `${item.id}${item.units ? ` · ${item.units}` : ''}` }))} onChange={(value) => actions.onHistoryChange('chartId', value)} /></Field><Field label="时间范围" htmlFor="nd-range"><Select id="nd-range" value={String(historyQuery.seconds)} disabled={busy} options={[['3600','最近 1 小时'],['86400','最近 1 天'],['604800','最近 7 天'],['2592000','最近 30 天']].map(([value,label]) => ({ value, label }))} onChange={(value) => actions.onHistoryChange('seconds', Number(value))} /></Field></div><Button variant="secondary" disabled={busy} onClick={actions.onQueryHistory}>查看曲线</Button>{history ? <HistoryGraph history={history} /> : null}</> : <EmptyState size="compact" title="选择节点查看历史" />}</section>
    </div><aside className="nd-section nd-install"><div className="nd-title"><h4>安装配置</h4><small>可选</small></div><Field label="目标机器" htmlFor="nd-host"><Combobox placeholder="搜索机器" id="nd-host" value={installDraft.hostId} disabled={busy} options={[...installHosts]} onChange={(value) => actions.onInstallChange('hostId', value)} /></Field><div className="nd-grid"><Field label="端口" htmlFor="nd-port"><NumberInput id="nd-port" value={installDraft.port} min={1024} max={65535} disabled={busy} onChange={(value) => actions.onInstallChange('port', Number(value))} /></Field><Field label="监听" htmlFor="nd-bind"><Select id="nd-bind" value={installDraft.bind} disabled={busy} options={[{value:'0.0.0.0',label:'所有网卡'},{value:'127.0.0.1',label:'仅本机'}]} onChange={(value) => actions.onInstallChange('bind', value)} /></Field><Field label="历史保留" htmlFor="nd-days"><Select id="nd-days" value={String(installDraft.retentionDays)} disabled={busy} options={[7,30,90].map((value)=>({value:String(value),label:`${value} 天`}))} onChange={(value) => actions.onInstallChange('retentionDays', Number(value))} /></Field><Field label="容量" htmlFor="nd-disk"><Select id="nd-disk" value={String(installDraft.diskMiB)} disabled={busy} options={[512,1024,2048,4096].map((value)=>({value:String(value),label:value<1024?`${value} MiB`:`${value/1024} GiB`}))} onChange={(value) => actions.onInstallChange('diskMiB', Number(value))} /></Field></div><div className="nd-actions"><Button variant="secondary" disabled={busy} onClick={actions.onPreviewInstall}>预览安装</Button>{installPreview ? <Button variant="primary" disabled={busy} onClick={actions.onConfirmInstall}>确认安装</Button> : null}</div>{installPreview ? <pre className="nd-plan">目标：{installPreview.name} ({installPreview.alias}){`\n\n`}{installPreview.command}</pre> : <p className="nd-note">已有安装会快速检测并跳过，不会重复改写配置。</p>}</aside></div>
    {state.status !== 'idle' ? <p className={cx(statusClass)} role={state.status === 'error' ? 'alert' : 'status'}>{state.message}</p> : null}
  </section>;
}
