document.body.innerHTML=`
<header><div><div class="eyebrow">LOCAL CONTAINER WORKSPACE</div><h1>Docker 管理 <span id="context">正在连接</span></h1><p>按项目组织容器，查看服务与镜像。</p></div><div class="header-actions"><button id="desktop">桌面悬浮窗</button><button id="theme" aria-label="切换浅色或深色外观">外观</button><button id="refresh">↻ 刷新</button></div></header>
<div id="preview" hidden>只读模拟预览 · 不连接 Docker，不执行操作</div><div id="notice" role="status" hidden></div>
<section class="summary" aria-label="容器概况"><div><span>全部容器</span><strong id="total">—</strong></div><div><span>运行中</span><strong id="running">—</strong></div><div><span>需要关注</span><strong id="issues">—</strong></div><div><span>Compose 项目</span><strong id="projects">—</strong></div></section>
<nav class="scope-tabs" aria-label="资源类型"><button data-scope="all" class="active">全部</button><button data-scope="compose">Compose</button><button data-scope="standalone">独立容器</button><button data-scope="images">镜像</button><button data-scope="settings">通用设置</button></nav>
<main><aside><div class="list-head"><h2 id="listTitle">项目与容器</h2><span id="updated">尚未更新</span></div><input id="filter" type="search" placeholder="搜索名称、镜像或项目" aria-label="搜索资源"><div id="containers" aria-label="资源列表"></div></aside>
<section class="detail"><div id="empty" class="empty large"><div class="cube">◇</div><h2>选择项目、容器或镜像</h2><p>点击名称查看详情，箭头控制项目展开。</p></div><div id="selection" hidden><div class="detail-head"><div><span id="service" class="eyebrow"></span><h2 id="name"></h2><p id="image"></p></div><span id="state" class="badge"></span></div><div id="actions" class="actions"></div><nav id="detailTabs" aria-label="容器详情"><button data-tab="overview" class="active">概览</button><button data-tab="logs">运行日志</button></nav><div id="overview"></div><div id="logsPanel" hidden><div class="log-tools"><input id="logFilter" type="search" placeholder="过滤日志内容" aria-label="过滤日志"><label><input id="follow" type="checkbox"> 每 3 秒刷新</label><button id="reloadLogs">刷新日志</button></div><p class="hint">最近 300 行 · stdout / stderr 分段展示 · 最多各 512 KiB</p><pre id="logs" tabindex="0"></pre></div></div></section></main>
<section id="settingsPanel" class="settings-panel" hidden aria-labelledby="settingsTitle"><div class="settings-heading"><div><span class="eyebrow">DOCKER / DEFAULTS</span><h2 id="settingsTitle">通用设置</h2><p>这里控制 Docker 管理主面板的默认行为；悬浮窗仍可单独配置显示范围。</p></div><span id="settingsSaved" class="settings-saved" role="status"></span></div><form id="settingsForm"><label>刷新频率<select id="settingRefresh"><option value="15">每 15 秒</option><option value="30">每 30 秒</option><option value="60">每 60 秒</option><option value="120">每 2 分钟</option></select><small>后台采集仍由插件统一维护，这里控制页面刷新频率。</small></label><label>打开时的默认范围<select id="settingScope"><option value="all">全部资源</option><option value="compose">Compose 项目</option><option value="standalone">独立容器</option><option value="images">镜像</option></select></label><label class="check"><input id="settingIssues" type="checkbox"> 默认只显示异常容器</label><label class="check"><input id="settingExpand" type="checkbox"> 默认展开 Compose 项目</label><label>主题<select id="settingTheme"><option value="system">跟随系统</option><option value="light">浅色</option><option value="dark">深色</option></select></label><div class="settings-actions"><button type="submit" class="primary">保存设置</button><button type="button" id="resetSettings">恢复默认</button></div></form><div class="settings-note"><strong>当前 Docker 环境</strong><span id="settingsContext">尚未连接</span><small>Docker context 由本机 Docker CLI 管理，主面板会在环境发生变化时清除当前选择。</small></div></section>
<footer>仅连接本机 Docker 环境 <span>列表每 15 秒更新 · 删除前需确认</span></footer>
<dialog id="confirm"><form method="dialog"><h2 id="confirmTitle"></h2><p id="confirmText"></p><div class="dialog-actions"><button value="cancel">取消</button><button value="confirm" class="primary">确认操作</button></div></form></dialog>`;
