use serde::{Deserialize,Serialize};
use serde_json::{json,Value};
use std::{collections::BTreeMap,time::{Duration,Instant}};
#[derive(Clone,PartialEq,Serialize,Deserialize)]
pub(crate) struct Endpoint { pub url:String, #[serde(default)] pub device:String }
impl Endpoint {pub fn validate(&self)->Result<(),String>{let u=url::Url::parse(&self.url).map_err(|_|"请输入完整的 metrics 地址")?;if !["http","https"].contains(&u.scheme())||u.host_str().is_none()||!u.username().is_empty()||u.password().is_some()||u.fragment().is_some()||self.url.len()>2048||self.device.len()>100{return Err("Node Exporter 地址或网卡无效".into());}Ok(())}}
#[derive(Default)]struct Sample {cpu:BTreeMap<String,f64>,rx:BTreeMap<String,f64>,tx:BTreeMap<String,f64>,ram:f64,available:f64,size:f64,free:f64,boot:f64,load:f64}
fn labels(text:&str)->Result<BTreeMap<String,String>,String>{
    let mut result=BTreeMap::new();let mut rest=text.trim();while !rest.is_empty(){let (key,value)=rest.split_once('=').ok_or("标签格式无效")?;let value=value.trim_start();if !value.starts_with('"'){return Err("标签缺少引号".into());}let mut escaped=false;let mut end=None;for (i,c) in value.char_indices().skip(1){if escaped{escaped=false;}else if c=='\\'{escaped=true;}else if c=='"'{end=Some(i+1);break;}}
      let end=end.ok_or("标签引号未闭合")?;let decoded:String=serde_json::from_str(&value[..end]).map_err(|_|"标签转义无效")?;result.insert(key.trim().to_owned(),decoded);rest=value[end..].trim_start();if rest.is_empty(){break;}rest=rest.strip_prefix(',').ok_or("标签分隔符无效")?.trim_start();}Ok(result)
}
fn parse(text:&str,device:&str)->Result<Sample,String>{let mut s=Sample::default();for line in text.lines(){let line=line.trim();if !line.starts_with("node_"){continue;}
    let name_end=line.find(|c:char|c=='{'||c.is_whitespace()).unwrap_or(line.len());let name=&line[..name_end];let tail=&line[name_end..];
    if !["node_cpu_seconds_total","node_memory_MemTotal_bytes","node_memory_MemAvailable_bytes","node_filesystem_size_bytes","node_filesystem_avail_bytes","node_network_receive_bytes_total","node_network_transmit_bytes_total","node_boot_time_seconds","node_load1"].contains(&name){continue;}
    let (l,value)=if tail.starts_with('{'){let mut quoted=false;let mut escaped=false;let mut end=None;for(i,c)in tail.char_indices().skip(1){if escaped{escaped=false;continue;}if c=='\\'&&quoted{escaped=true;}else if c=='"'{quoted=!quoted;}else if c=='}'&&!quoted{end=Some(i);break;}}let end=end.ok_or("指标标签未闭合")?;(labels(&tail[1..end])?,tail[end+1..].trim())}else{(BTreeMap::new(),tail.trim())};
    let Some(v)=value.split_whitespace().next().and_then(|v|v.parse::<f64>().ok()).filter(|v|v.is_finite()&&*v>=0.)else{continue};
    match name {"node_cpu_seconds_total"=>{let mode=l.get("mode").map(String::as_str).unwrap_or("");if !["guest","guest_nice"].contains(&mode){s.cpu.insert(format!("{}:{mode}",l.get("cpu").map(String::as_str).unwrap_or("")),v);}},"node_memory_MemTotal_bytes"=>s.ram=v,"node_memory_MemAvailable_bytes"=>s.available=v,"node_filesystem_size_bytes" if l.get("mountpoint").map(String::as_str)==Some("/")=>s.size=v,"node_filesystem_avail_bytes" if l.get("mountpoint").map(String::as_str)==Some("/")=>s.free=v,"node_boot_time_seconds"=>s.boot=v,"node_load1"=>s.load=v,
    "node_network_receive_bytes_total"|"node_network_transmit_bytes_total"=>{if let Some(d)=l.get("device"){if (!device.is_empty()&&d==device)||(device.is_empty()&&d!="lo"&&!d.starts_with("veth")&&!d.starts_with("docker")&&!d.starts_with("br-")){if name=="node_network_receive_bytes_total"{s.rx.insert(d.clone(),v);}else{s.tx.insert(d.clone(),v);}}}},_=>{}}
 }if s.cpu.is_empty()||s.ram<=0.{return Err("未找到 Node Exporter 的 CPU 和内存指标".into());}Ok(s)}
fn delta(a:&BTreeMap<String,f64>,b:&BTreeMap<String,f64>)->Option<f64>{if a.keys().ne(b.keys()){return None;}let mut sum=0.;for(k,v)in b{let d=v-a[k];if d<0.{return None;}sum+=d;}Some(sum)}
fn values(a:&Sample,b:&Sample,seconds:f64)->Value {let total=delta(&a.cpu,&b.cpu);let idle=|s:&Sample|s.cpu.iter().filter(|(k,_)|k.ends_with(":idle")||k.ends_with(":iowait")).map(|(k,v)|(k.clone(),*v)).collect();let idle=delta(&idle(a),&idle(b));json!({"cpu":total.zip(idle).filter(|(t,_)|*t>0.).map(|(t,i)|((t-i)/t*100.).clamp(0.,100.)),"memory":((b.ram-b.available)/b.ram*100.).clamp(0.,100.),"disk":if b.size>0.{Some(((b.size-b.free)/b.size*100.).clamp(0.,100.))}else{None},"load":b.load,"uptime":if b.boot>0.{Some((chrono::Utc::now().timestamp() as f64-b.boot).max(0.))}else{None},"rx":delta(&a.rx,&b.rx).filter(|_|!b.rx.is_empty()).map(|v|v/seconds/1000.),"tx":delta(&a.tx,&b.tx).filter(|_|!b.tx.is_empty()).map(|v|v/seconds/1000.)})}
async fn read(client:&reqwest::Client,endpoint:&Endpoint)->Result<Sample,String>{let mut response=client.get(&endpoint.url).header("Accept","text/plain; version=0.0.4").send().await.map_err(|e|format!("Exporter 连接失败：{e}"))?.error_for_status().map_err(|e|format!("Exporter 响应失败：{e}"))?;let mut bytes=Vec::new();while let Some(chunk)=response.chunk().await.map_err(|e|e.to_string())?{if bytes.len()+chunk.len()>8*1024*1024{return Err("Exporter 响应超过 8 MiB".into());}bytes.extend_from_slice(&chunk);}parse(std::str::from_utf8(&bytes).map_err(|_|"指标不是 UTF-8")?,&endpoint.device)}
pub(crate) async fn collect(endpoint:&Endpoint)->Result<Value,String>{endpoint.validate()?;let client=reqwest::Client::builder().timeout(Duration::from_secs(8)).redirect(reqwest::redirect::Policy::none()).build().map_err(|e|e.to_string())?;let a=read(&client,endpoint).await?;let start=Instant::now();tokio::time::sleep(Duration::from_secs(1)).await;let b=read(&client,endpoint).await?;Ok(values(&a,&b,start.elapsed().as_secs_f64()))}
#[cfg(test)]mod tests{use super::*;#[test]fn rates_resets_escaping_and_missing_mount(){let data=|user,idle,rx|format!("node_cpu_seconds_total{{mode=\"user\",cpu=\"0\"}} {user}\nnode_cpu_seconds_total{{cpu=\"0\",mode=\"idle\"}} {idle}\nnode_memory_MemTotal_bytes 100\nnode_memory_MemAvailable_bytes 75\nnode_network_receive_bytes_total{{device=\"eth0\"}} {rx}\n");let a=parse(&data(100,200,1000),"").unwrap();let b=parse(&data(110,230,5000),"").unwrap();let v=values(&a,&b,2.);assert_eq!(v["cpu"],25.);assert_eq!(v["rx"],2.);assert!(v["disk"].is_null());assert!(values(&b,&a,1.)["cpu"].is_null());assert_eq!(labels(r#"device="a\"b",mountpoint="/""#).unwrap()["device"],"a\"b");assert!(Endpoint{url:"file:///tmp/a".into(),device:String::new()}.validate().is_err());}}
