(()=>{
 const invoke=window.FlowHubPlugin?.invoke;if(!invoke)return;
 const api=(action,payload)=>invoke('machines_api',{action,payload});
 const button=document.createElement('button');button.type='button';button.textContent='腾讯云流量';document.querySelector('header .actions').prepend(button);
 const dialog=document.createElement('dialog');dialog.className='netdata-dialog';dialog.innerHTML=`<div class="section-head"><h2>腾讯云流量</h2><button data-close type="button">关闭</button></div><p class="netdata-note">为机器关联 Lighthouse 轻量实例。凭证加密保存，重新打开无需重复输入。组件流量每 5 分钟更新，也可在此手动查询。</p><label>关联机器<select data-host></select></label><form><div class="netdata-fields"><label>地域<input name="region" required placeholder="ap-shanghai"></label><label>轻量实例 ID<input name="instanceId" required placeholder="lhins-…"></label><label>SecretId<input name="secretId" autocomplete="off" placeholder="已保存时留空保留"></label><label>SecretKey<input name="secretKey" type="password" autocomplete="new-password" placeholder="已保存时留空保留"></label><label>临时 Token（可选）<input name="token" type="password" autocomplete="off" placeholder="留空保留"></label></div><label><input name="clearToken" type="checkbox">清除已保存的临时 Token</label><div class="actions"><button type="submit" class="primary">保存配置</button><button type="button" data-query>查询已保存配置</button></div></form><p data-status role="status"></p><section data-result></section>`;document.body.append(dialog);
 const $=s=>dialog.querySelector(s),form=$('form');let busy=false;
 function clearSecrets(){for(const k of ['secretId','secretKey','token'])form.elements[k].value='';form.elements.clearToken.checked=false;}
 async function run(fn){if(busy)return;busy=true;dialog.querySelectorAll('button,select,input').forEach(e=>e.disabled=true);try{await fn();}catch(e){$('[data-status]').textContent=e.message;}finally{busy=false;dialog.querySelectorAll('button,select,input').forEach(e=>e.disabled=false);}}
 async function load(){clearSecrets();$('[data-result]').replaceChildren();const v=await api('tencentRead',{hostId:$('[data-host]').value});form.elements.region.value=v.region||'ap-shanghai';form.elements.instanceId.value=v.instanceId||'';$('[data-status]').textContent=v.configured?'已保存 · 密钥留空保留，可直接查询':'尚未配置，请填写后保存';}
 button.onclick=()=>run(async()=>{const s=await api('state',{});const select=$('[data-host]');select.replaceChildren();for(const h of s.config.hosts){const o=document.createElement('option');o.value=h.id;o.textContent=h.name;select.append(o);}dialog.showModal();if(select.value)await load();else $('[data-status]').textContent='请先添加机器';});
 $('[data-close]').onclick=()=>dialog.close();dialog.addEventListener('close',clearSecrets);dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});$('[data-host]').onchange=()=>run(load);
 form.onsubmit=e=>{e.preventDefault();run(async()=>{const p={hostId:$('[data-host]').value};for(const k of ['region','instanceId','secretId','secretKey','token'])p[k]=form.elements[k].value.trim();p.clearToken=form.elements.clearToken.checked;await api('tencentSave',p);clearSecrets();$('[data-status]').textContent='配置已加密保存，关闭页面或重启后仍可查询';$('[data-result]').replaceChildren();});};
 $('[data-query]').onclick=()=>run(async()=>{const hostId=$('[data-host]').value;const saved=await api('tencentRead',{hostId});if(!saved.configured)throw Error('请先保存配置');if(['region','instanceId'].some(k=>form.elements[k].value.trim()!==saved[k])||['secretId','secretKey','token'].some(k=>form.elements[k].value)||form.elements.clearToken.checked)throw Error('配置有未保存修改，请先保存');$('[data-status]').textContent='正在查询腾讯云…';$('[data-result]').replaceChildren();const data=await api('tencentQuery',{hostId});const n=v=>Number.isFinite(v)?(v/1073741824).toLocaleString('zh-CN',{maximumFractionDigits:2}):'—';let count=0;for(const row of data.rows)for(const p of row.TrafficPackageSet||[]){count++;const card=document.createElement('article');card.className='panel';const title=document.createElement('h3');title.textContent=`剩余 ${n(p.TrafficPackageRemaining)} GiB`;const text=document.createElement('p');text.textContent=`${row.InstanceId} · 已用 ${n(p.TrafficUsed)} / ${n(p.TrafficPackageTotal)} GiB · 超额 ${n(p.TrafficOverflow)} GiB`;const period=document.createElement('p');period.textContent='周期结束：'+(p.EndTime?new Date(p.EndTime).toLocaleString():'—');card.append(title,text,period);$('[data-result]').append(card);}$('[data-status]').textContent=(count?'腾讯云官方查询完成':'该实例暂无流量包')+' · '+new Date(data.at).toLocaleString();});
})();
