(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const labels={healthy:'正常',error:'异常',stale:'已过期',unknown:'未采集'};
  function gauges(row,metrics){return '<div class="gauges">'+[['cpu','CPU'],['memory','内存'],['disk','磁盘']].filter(([key])=>metrics.includes(key)).map(([key,label])=>{const value=row.values?.[key],valid=typeof value==='number'&&Number.isFinite(value);return `<div class="gauge ${value>=85?'warning':''}"><svg viewBox="0 0 100 86" role="img" aria-label="${label} ${valid?value.toFixed(1)+'%':'无数据'}"><path class="track" d="M 16 67 A 39 39 0 1 1 84 67" pathLength="100"/><path class="fill" d="M 16 67 A 39 39 0 1 1 84 67" pathLength="100" stroke-dasharray="${valid?Math.max(0,Math.min(100,value)):0} 100"/><text x="50" y="48">${valid?Math.round(value)+'%':'—'}</text><text class="unit" x="50" y="65">${label}</text></svg></div>`;}).join('')+'</div>';}
  function network(card,row){if(card.view!=='machine')return '';return '<span class="header-network">'+[['tx','↑','上传'],['rx','↓','下载']].filter(([k])=>card.metrics?.includes(k)).map(([k,arrow,label])=>{const v=row?.values?.[k],text=Number.isFinite(v)?(v>=1000?(v/1000).toFixed(1)+' MB/s':v.toFixed(1)+' KB/s'):'—';return `<span title="${label}速率" aria-label="${label}速率 ${text}">${arrow} ${text}</span>`;}).join('')+'</span>';}
  function content(card,source){
    if(!source)return '<p class="empty">插件未启用 · 布局已保留</p>';
    const snapshot=source.snapshot;if(!snapshot)return '<p class="empty">正在等待插件状态…</p>';
    if(snapshot.error)return `<p class="empty">${esc(snapshot.error)}</p>`;
    const rows=Array.isArray(snapshot.rows)?snapshot.rows:[];
    if(card.view==='machine'){const row=rows.find(r=>r.id===card.row);if(!row)return '<p class="empty">目标已移除或尚无数据</p>';const metrics=card.metrics||['cpu','memory','disk'];return gauges(row,metrics)+(['load','uptime'].some(k=>metrics.includes(k))?'<div class="bottom-metrics">'+[['load','负载',''],['uptime','运行','天']].filter(([k])=>metrics.includes(k)).map(([k,label,unit])=>`<span>${label} ${Number.isFinite(row.values?.[k])?(k==='uptime'?(row.values[k]/86400).toFixed(1):row.values[k].toFixed(1)):'—'}${unit}</span>`).join('')+'</div>':'')+`<div class="widget-foot"><span class="${Object.hasOwn(labels,row.status)?row.status:'unknown'}">● ${labels[row.status]||'未知'}</span><span id="expiry" hidden></span></div>`;}
    if(card.view==='overview')return `<div class="overview-total">${rows.length}<small>个实例</small></div><div class="overview-status"><span class="healthy">● ${rows.filter(r=>r.status==='healthy').length} 正常</span><span class="error">${rows.filter(r=>r.status==='error'||r.status==='stale').length} 异常 / 过期</span></div>`;
    const visible=card.view==='alerts'?rows.filter(r=>r.status!=='healthy'):rows;
    return visible.map(r=>`<div class="row"><div class="row-head"><b>${esc(r.name)}</b><span class="${Object.hasOwn(labels,r.status)?r.status:'unknown'}">● ${labels[r.status]||'未知'}</span></div><div class="values">${Object.entries(r.values||{}).filter(([,v])=>typeof v==='number'&&Number.isFinite(v)).slice(0,5).map(([k,v])=>`<span><small>${esc({cpu:'CPU',memory:'内存',disk:'磁盘',load:'负载',uptime:'运行秒数'}[k]||k)}</small>${esc(v.toLocaleString(undefined,{maximumFractionDigits:1}))}${['cpu','memory','disk'].includes(k)?'%':''}</span>`).join('')}</div><time>${r.at?esc(new Date(r.at).toLocaleTimeString()):'尚无采集数据'}</time></div>`).join('')||`<p class="empty">${card.view==='alerts'?'当前没有异常':'暂无状态数据'}</p>`;
  }

let currentRow,showExpiry=true;const updateExpiry=()=>{const node=document.querySelector('#expiry');if(!node)return;const expiry=showExpiry?MachineMetadata.expiry(currentRow?.expiresAt):null;node.hidden=!expiry;if(expiry){node.textContent=expiry.text;node.className='expiry'+(expiry.expired?' expired':expiry.urgent?' urgent':'');node.title='到期时间：'+new Date(currentRow.expiresAt).toLocaleString();}};setInterval(updateExpiry,60000);
FlowHubWidget.onInit(data=>{const source={title:'机器管理',snapshot:data.snapshot},card={...data.config,title:data.title};if(!card.view||card.view==='widget')card.view='machine';if(!card.row)card.row=source.snapshot?.rows?.[0]?.id;const row=source.snapshot?.rows?.find(r=>r.id===card.row);currentRow=card.view==='machine'?row:null;showExpiry=card.showExpiry!==false;document.querySelector('#title').textContent=[card.showCountry!==false?MachineMetadata.flag(currentRow?.countryCode):'',card.title||row?.name||'机器管理'].filter(Boolean).join(' ');document.querySelector('#network').innerHTML=network(card,row);document.querySelector('#content').innerHTML=content(card,source);updateExpiry();});
})();
