(() => {
  const $ = (selector) => document.querySelector(selector);
  const preview = parent === window;
  let accounts = [], selected = "", editing = null, timer;
  const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  document.body.innerHTML = `
    <header><div><span class="eyebrow">FLOWHUB / SECURITY UTILITY</span><h1>2FA 验证码</h1><p>集中管理本机保存的验证器，点击名称即可查看当前验证码。</p></div><button id="add" class="primary">＋ 添加配置</button></header>
    <div id="notice" class="notice" role="status"></div>
    <main class="workspace"><section class="panel list-panel"><div class="panel-heading"><div><h2>已配置的验证器</h2><p class="hint">密钥仅保存在本机加密文件中</p></div><span id="count" class="count"></span></div><div id="accounts" class="accounts"></div></section>
    <section class="panel detail-panel"><div class="panel-heading"><h2>验证码</h2><span id="detailName" class="muted">未选择</span></div><div id="code" class="code"><div class="empty">从左侧选择一个名称</div></div><form id="command" class="command"><input id="query" placeholder="输入名称快速查询" autocomplete="off"><button>查询</button></form></section></main>
    <section id="editor" class="panel editor" hidden><div class="panel-heading"><div><h2 id="editorTitle">添加 2FA 配置</h2><p class="hint">支持标准 Base32 TOTP 密钥</p></div><button id="cancel">取消</button></div><form id="form"><label>名称<input id="name" required maxlength="80" placeholder="例如 cloud-cd"></label><label>Base32 密钥<input id="secret" required autocomplete="off" placeholder="JBSWY3DPEHPK3PXP"></label><label>发行方（可选）<input id="issuer" maxlength="120" placeholder="Bilibili"></label><div class="editor-actions"><button type="button" id="cancelBottom">取消</button><button class="primary" type="submit">保存配置</button></div></form></section>`;
  const notice = (message = "") => { $("#notice").textContent = message; };
  async function call(method, params = {}) { if (preview) { if (method === "list") return { accounts: [{ name: "cloud-cd", issuer: "模拟" }] }; if (method === "code") return { name: params.name, code: "123456", remaining: 18, issuer: "模拟" }; throw Error("浏览器预览不保存真实密钥"); } return FlowHubPlugin.invoke(method, params); }
  function renderAccounts() { $("#count").textContent = `${accounts.length} 个`; $("#accounts").innerHTML = accounts.length ? accounts.map((account) => `<article class="account ${account.name === selected ? "selected" : ""}" data-name="${esc(account.name)}"><button class="account-main" data-action="select"><strong>${esc(account.name)}</strong><small>${esc(account.issuer || "未设置发行方")}</small></button><div class="account-actions"><button class="icon-button" data-action="edit" aria-label="编辑 ${esc(account.name)}">编辑</button><button class="icon-button danger" data-action="remove" aria-label="删除 ${esc(account.name)}">删除</button></div></article>`).join("") : '<div class="empty list-empty">还没有配置，点击右上角“添加配置”开始。</div>'; }
  async function showCode(name) { selected = name; renderAccounts(); $("#detailName").textContent = name || "未选择"; if (!name) { $("#code").innerHTML = '<div class="empty">从左侧选择一个名称</div>'; return; } try { const result = await call("code", { name }); $("#code").innerHTML = `<strong>${esc(result.code)}</strong><span>${esc(result.name)}${result.issuer ? ` · ${esc(result.issuer)}` : ""}</span><small>将在 ${result.remaining} 秒后自动刷新</small>`; } catch (error) { $("#code").innerHTML = `<div class="empty">${esc(error.message)}</div>`; } }
  async function refresh() { try { const result = await call("list"); accounts = result.accounts || []; if (!selected || !accounts.some((account) => account.name === selected)) selected = accounts[0]?.name || ""; renderAccounts(); await showCode(selected); } catch (error) { notice(error.message); } }
  function closeEditor() { editing = null; $("#editor").hidden = true; }
  function openEditor(account = null) { editing = account?.name || null; $("#editor").hidden = false; $("#editorTitle").textContent = account ? "编辑 2FA 配置" : "添加 2FA 配置"; $("#name").value = account?.name || ""; $("#name").readOnly = false; $("#secret").value = ""; $("#secret").required = !account; $("#secret").placeholder = account ? "留空则保留原密钥" : "JBSWY3DPEHPK3PXP"; $("#issuer").value = account?.issuer || ""; $("#name").focus(); }
  $("#add").onclick = () => openEditor(); $("#cancel").onclick = $("#cancelBottom").onclick = closeEditor;
  $("#accounts").onclick = async (event) => { const row = event.target.closest("[data-name]"); const action = event.target.closest("[data-action]")?.dataset.action; if (!row) return; const name = row.dataset.name; if (action === "edit") return openEditor(accounts.find((account) => account.name === name)); if (action === "remove") { if (preview || !confirm(`删除 ${name}？`)) return; try { await call("remove", { name }); if (selected === name) selected = ""; await refresh(); notice("已删除"); } catch (error) { notice(error.message); } return; } await showCode(name); };
  $("#command").onsubmit = async (event) => { event.preventDefault(); const name = $("#query").value.trim().replace(/^2fa\s+/i, ""); if (name) await showCode(name); };
  $("#form").onsubmit = async (event) => { event.preventDefault(); try { const payload = { name: $("#name").value.trim(), secret: $("#secret").value.trim(), issuer: $("#issuer").value.trim() || null }; if (editing) payload.previous = editing; await call("save", payload); const wasEditing = Boolean(editing); selected = payload.name; closeEditor(); await refresh(); notice(wasEditing ? "配置已更新" : "配置已添加"); } catch (error) { notice(error.message); } };
  timer = setInterval(() => { if (selected) showCode(selected); }, 1000); addEventListener("beforeunload", () => clearInterval(timer)); refresh();
})();
