use ring::{aead, hmac, rand::{SecureRandom, SystemRandom}};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::{fs::{self, OpenOptions}, io::{self, BufRead, Write}, os::unix::fs::{OpenOptionsExt, PermissionsExt}, path::{Path, PathBuf}, time::{SystemTime, UNIX_EPOCH}};

#[derive(Clone, Serialize, Deserialize)] struct Entry { name:String, secret:String, issuer:Option<String> }
fn root()->Result<PathBuf,String>{std::env::var_os("FLOWHUB_PLUGIN_DATA").map(PathBuf::from).ok_or("缺少 FLOWHUB_PLUGIN_DATA".into())}
fn secure(path:&Path)->Result<(),String>{let m=fs::symlink_metadata(path).map_err(|e|e.to_string())?;if !m.is_file()||m.permissions().mode()&0o077!=0{return Err(format!("文件权限不安全：{}",path.display()))}Ok(())}
fn key(root:&Path,create:bool)->Result<aead::LessSafeKey,String>{let p=root.join("twofa.key");if !p.exists()&&create{fs::create_dir_all(root).map_err(|e|e.to_string())?;let mut b=[0;32];SystemRandom::new().fill(&mut b).map_err(|_|"无法生成加密密钥")?;let mut f=OpenOptions::new().write(true).create_new(true).mode(0o600).open(&p).map_err(|e|e.to_string())?;f.write_all(&b).map_err(|e|e.to_string())?;f.sync_all().map_err(|e|e.to_string())?;}secure(&p)?;let b=fs::read(p).map_err(|e|e.to_string())?;Ok(aead::LessSafeKey::new(aead::UnboundKey::new(&aead::AES_256_GCM,&b).map_err(|_|"密钥损坏")?))}
fn load(root:&Path)->Result<Vec<Entry>,String>{let p=root.join("twofa.secrets");if !p.exists(){return Ok(vec![])}secure(&p)?;let mut b=fs::read(p).map_err(|e|e.to_string())?;if b.len()<12{return Err("2FA 密钥文件损坏".into())}let nonce:[u8;12]=b[..12].try_into().unwrap();let key=key(root,false)?;let plain=key.open_in_place(aead::Nonce::assume_unique_for_key(nonce),aead::Aad::from(b"flowhub-twofa-v1"),&mut b[12..]).map_err(|_|"2FA 密钥无法解密")?;serde_json::from_slice(plain).map_err(|_|"2FA 配置格式损坏".into())}
fn save(root:&Path,entries:&[Entry])->Result<(),String>{fs::create_dir_all(root).map_err(|e|e.to_string())?;let key=key(root,true)?;let mut nonce=[0;12];SystemRandom::new().fill(&mut nonce).map_err(|_|"无法生成随机数")?;let mut c=serde_json::to_vec(entries).map_err(|e|e.to_string())?;key.seal_in_place_append_tag(aead::Nonce::assume_unique_for_key(nonce),aead::Aad::from(b"flowhub-twofa-v1"),&mut c).map_err(|_|"2FA 配置加密失败")?;let p=root.join("twofa.secrets");let tmp=root.join("twofa.secrets.tmp");let mut f=OpenOptions::new().write(true).create(true).truncate(true).mode(0o600).open(&tmp).map_err(|e|e.to_string())?;f.write_all(&nonce).and_then(|_|f.write_all(&c)).and_then(|_|f.sync_all()).map_err(|e|e.to_string())?;fs::rename(tmp,p).map_err(|e|e.to_string())}
fn valid_name(s:&str)->bool{!s.is_empty()&&s.len()<=80&&!s.chars().any(char::is_control)}
fn base32(s:&str)->Result<Vec<u8>,String>{let mut bits=0u32;let mut n=0u8;let mut out=Vec::new();for c in s.chars().filter(|c|*c!='-'&&*c!=' '&&*c!='='){let upper=c.to_ascii_uppercase();let v=match upper{'A'..='Z'=>upper as u8-b'A','2'..='7'=>upper as u8-b'2'+26,_=>return Err("TOTP 密钥必须是 Base32".into())};bits=(bits<<5)|v as u32;n+=5;if n>=8{n-=8;out.push((bits>>n) as u8);}}if out.len()<10{return Err("TOTP 密钥过短".into())}Ok(out)}
fn code(secret:&str,at:u64)->Result<(String,u64),String>{let key=base32(secret)?;let counter=at/30;let mut msg=[0u8;8];msg.copy_from_slice(&counter.to_be_bytes());let tag=hmac::sign(&hmac::Key::new(hmac::HMAC_SHA1_FOR_LEGACY_USE_ONLY,&key),&msg);let b=tag.as_ref();let o=(b[19]&15) as usize;let n=((u32::from(b[o])&127)<<24)|(u32::from(b[o+1])<<16)|(u32::from(b[o+2])<<8)|u32::from(b[o+3]);Ok((format!("{:06}",n%1_000_000),30-(at%30)))}
fn now()->u64{SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs()}
fn dispatch(method:&str,p:&Value)->Result<Value,String>{let root=root()?;match method{"health"=>Ok(json!({"protocol":1,"name":"twofa","version":"0.1.0"})),"list"=>Ok(json!({"accounts":load(&root)?.into_iter().map(|e|json!({"name":e.name,"issuer":e.issuer})).collect::<Vec<_>>()})),"save"=>{let name=p["name"].as_str().unwrap_or("").trim();let secret=p["secret"].as_str().unwrap_or("").trim();if !valid_name(name){return Err("名称不能为空且不能超过 80 个字符".into())}base32(secret)?;let mut all=load(&root)?;all.retain(|e|e.name!=name);all.push(Entry{name:name.into(),secret:secret.into(),issuer:p["issuer"].as_str().map(str::to_owned)});all.sort_by(|a,b|a.name.cmp(&b.name));save(&root,&all)?;Ok(json!({"saved":true}))},"remove"=>{let name=p["name"].as_str().unwrap_or("");let mut all=load(&root)?;let n=all.len();all.retain(|e|e.name!=name);if n==all.len(){return Err("未找到该 2FA 名称".into())}save(&root,&all)?;Ok(json!({"removed":true}))},"code"=>{let name=p["name"].as_str().unwrap_or("");let e=load(&root)?.into_iter().find(|e|e.name==name).ok_or("未找到该 2FA 名称")?;let (value,remaining)=code(&e.secret,now())?;Ok(json!({"name":e.name,"issuer":e.issuer,"code":value,"remaining":remaining}))},_=>Err("未知操作".into())}}
fn main()->Result<(),Box<dyn std::error::Error>>{let stdin=io::stdin();for line in stdin.lock().lines(){let line=line?;let req:Value=serde_json::from_str(&line)?;let result=dispatch(req["method"].as_str().unwrap_or(""),&req["params"]);let out=match result{Ok(v)=>json!({"id":req["id"],"result":v}),Err(e)=>json!({"id":req["id"],"error":e})};println!("{out}");}Ok(())}

#[cfg(test)] mod tests{use super::*;#[test]fn known_totp(){let (c,left)=code("GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ",59).unwrap();assert_eq!(c,"287082");assert!(left>0&&left<=30)}#[test]fn rejects_bad_secret(){assert!(base32("no!").is_err())}}
