(() => {
 const invoke=window.FlowHubPlugin?.invoke||window.__TAURI__?.core?.invoke;
 const open=document.createElement('button');open.type='button';open.textContent='监控设置';document.querySelector('header .actions').prepend(open);
 const dialog=document.createElement('dialog');dialog.className='netdata-dialog';dialog.innerHTML=`<div class="section-head"><h2>监控设置</h2><button data-close>关闭</button></div><p class="netdata-note">FlowHub 运行且开启后台监控时定时采集，也可手动采集。未运行期间保留空档，不补造历史。</p><form data-settings><label>历史保留时长（天）<input data-days type="number" min="1" max="365" value="30" required></label><p class="netdata-note">默认 30 天，可设 1–365 天。缩短时长会清理过期监控数据；最多保留 20 万条采样，空间可被后续采样复用。命令执行记录不受此设置影响。</p><h3>机器采集来源</h3><p class="netdata-note">有 Node Exporter 就填写完整 metrics 地址；留空沿用 SSH。地址必须能从本机访问。配置后连接失败会报错，不自动切换来源。</p><div data-sources></div><button type="submit">保存监控设置</button></form><section><h3>本地历史曲线</h3><div class="netdata-fields"><label>机器<select data-host></select></label><label>指标<select data-metric><option value="cpu">CPU 使用率</option><option value="memory">内存使用率</option><option value="disk">根磁盘使用率</option><option value="load">负载</option><option value="rx">下载速率</option><option value="tx">上传速率</option></select></label><label>时间范围<select data-range><option value="3600">最近 1 小时</option><option value="86400" selected>最近 1 天</option><option value="604800">最近 7 天</option><option value="2592000">最近 30 天</option><option value="7776000">最近 90 天</option></select></label></div><button data-query>查看曲线</button><div data-graph></div></section><pre data-status role="status"></pre>`;document.body.append(dialog);
 const $=s=>dialog.querySelector(s),api=(action,payload={})=>invoke('machines_api',{action,payload});let busy=false;
 const option=(value,text)=>{const o=document.createElement('option');o.value=value;o.textContent=text;return o;};
 async function run(work){if(busy)return;busy=true;dialog.querySelectorAll('button:not([data-close])').forEach(b=>b.disabled=true);try{await work();}catch(e){$('[data-status]').textContent=String(e);}finally{busy=false;dialog.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 async function load(){const state=await api('state');$('[data-days]').value=state.config.retentionDays||30;$('[data-sources]').replaceChildren();$('[data-host]').replaceChildren();for(const host of state.config.hosts||[]){$('[data-host]').append(option(host.id,host.name));const row=document.createElement('fieldset');row.dataset.sourceHost=host.id;const legend=document.createElement('legend');legend.textContent=host.name;const label=document.createElement('label');label.textContent='Node Exporter 地址（可选）';const input=document.createElement('input');input.type='url';input.placeholder='http://机器地址:9100/metrics';input.dataset.url='';input.value=state.config.exporters?.[host.id]?.url||'';label.append(input);const deviceLabel=document.createElement('label');deviceLabel.textContent='网卡（可选，留空汇总常见非虚拟网卡）';const device=document.createElement('input');device.dataset.device='';device.maxLength=100;device.placeholder='例如 eth0';device.value=state.config.exporters?.[host.id]?.device||'';deviceLabel.append(device);const test=document.createElement('button');test.type='button';test.textContent='测试 Exporter';test.onclick=()=>run(async()=>{if(!input.value.trim())throw Error('请先填写 Node Exporter 地址');$('[data-status]').textContent='正在读取两次采样…';const v=await api('exporterTest',{url:input.value.trim(),device:device.value.trim()});$('[data-status]').textContent=`${host.name}：连接成功\n${JSON.stringify(v,null,2)}`;});row.append(legend,label,deviceLabel,test);$('[data-sources]').append(row);}}
 open.onclick=()=>{dialog.showModal();if(invoke)run(load);else $('[data-status]').textContent='请在 FlowHub 中配置监控';};$('[data-close]').onclick=()=>dialog.close();
 $('[data-settings]').onsubmit=e=>{e.preventDefault();if(!invoke)return;run(async()=>{const exporters={};dialog.querySelectorAll('[data-sources] fieldset').forEach(row=>{const url=row.querySelector('[data-url]').value.trim();if(url)exporters[row.dataset.sourceHost]={url,device:row.querySelector('[data-device]').value.trim()};});await api('monitorSettings',{days:Number($('[data-days]').value),exporters});$('[data-status]').textContent='监控设置已保存，过期数据已清理。开启机器列表的后台监控后将定时采集。';});};
 $('[data-query]').onclick=()=>{if(!invoke)return;run(async()=>{const data=await api('metricHistory',{hostId:$('[data-host]').value,metric:$('[data-metric]').value,seconds:Number($('[data-range]').value)});const rows=data.data||[],valid=rows.filter(r=>Number.isFinite(r[1]));const root=$('[data-graph]');root.replaceChildren();if(!valid.length){root.textContent='此时间范围暂无已保存的采样。';return;}const max=Math.max(1,...valid.map(r=>r[1])),min=Math.min(0,...valid.map(r=>r[1]));const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.classList.add('netdata-graph');svg.setAttribute('viewBox','0 0 700 230');svg.setAttribute('role','img');svg.setAttribute('aria-label','本地监控历史曲线');let d='',pen=false;rows.forEach((r,i)=>{if(!Number.isFinite(r[1])){pen=false;return;}const x=40+i/(rows.length-1||1)*640,y=190-(r[1]-min)/(max-min||1)*170;d+=`${pen?'L':'M'}${x},${y} `;pen=true;const dot=document.createElementNS(ns,'circle');dot.setAttribute('cx',x);dot.setAttribute('cy',y);dot.setAttribute('r','2');dot.setAttribute('fill','#b0d8bd');const title=document.createElementNS(ns,'title');title.textContent=new Date(r[0]*1000).toLocaleString()+' · '+r[1].toFixed(2)+' '+data.unit;dot.append(title);svg.append(dot);});const path=document.createElementNS(ns,'path');path.setAttribute('d',d);path.setAttribute('stroke','#b0d8bd');path.setAttribute('fill','none');svg.append(path);[[4,15,max.toFixed(1)+' '+data.unit],[4,193,min.toFixed(1)],[40,218,new Date(rows[0][0]*1000).toLocaleString()],[465,218,new Date(rows.at(-1)[0]*1000).toLocaleString()]].forEach(([x,y,value])=>{const t=document.createElementNS(ns,'text');t.setAttribute('x',x);t.setAttribute('y',y);t.setAttribute('fill','#afc4b8');t.setAttribute('font-size','10');t.textContent=value;svg.append(t);});root.append(svg);$('[data-status]').textContent='历史读取完成，缺失采样显示为空档。';});};
})();
