(() => {
  const invoke=window.FlowHubPlugin?.invoke||window.__TAURI__?.core?.invoke;
  const button=document.createElement('button');button.textContent='Netdata 监控';button.type='button';document.querySelector('header .actions').prepend(button);
  const dialog=document.createElement('dialog');dialog.className='netdata-dialog';dialog.innerHTML=`<div class="section-head"><h2>Netdata 监控</h2><button type="button" data-dismiss>关闭</button></div>
  <p class="netdata-note">每台机器连接自己的 Agent，历史数据保留在远端，关闭 FlowHub 后仍继续采集。</p><div data-instances></div>
  <form data-connect><h3>接入已有 Netdata</h3><div class="netdata-fields"><label>机器名称<input name="name" required maxlength="40" placeholder="生产服务器"></label><label>Agent 地址<input name="url" required type="url" placeholder="http://机器地址:19999"></label></div><label>网速指标<select name="network"><option value="system.net">所有物理网卡 · system.net</option></select></label><div class="actions"><button type="button" data-test>测试并发现指标</button><button type="submit">保存节点</button><button type="button" data-reset>清空</button></div></form>
  <section data-history hidden><h3>历史趋势</h3><div class="netdata-fields"><label>指标<select data-chart></select></label><label>时间范围<select data-range><option value="3600">最近 1 小时</option><option value="86400" selected>最近 1 天</option><option value="604800">最近 7 天</option><option value="2592000">最近 30 天</option></select></label></div><button data-query>查看曲线</button><div data-graph></div><p class="netdata-note">显示 Agent 实际保存的数据；缺失的历史不会补造。</p></section>
  <details><summary>在机器上安装 Netdata</summary><form data-install><label>目标机器<select name="host" required></select></label><div class="netdata-fields"><label>端口<input name="port" type="number" min="1024" max="65535" value="19999" required></label><label>监听范围<select name="bind"><option value="127.0.0.1">仅本机 · 使用 SSH 转发</option><option value="0.0.0.0">所有网卡 · 在可信网络访问</option></select></label><label>历史保留<select name="days"><option value="7">7 天</option><option value="30">30 天</option><option value="90">90 天</option></select></label><label>指标存储目标容量<select name="disk"><option value="512">512 MiB</option><option value="1024" selected>1 GiB</option><option value="2048">2 GiB</option><option value="4096">4 GiB</option></select></label></div><p class="netdata-note">需要 Linux、curl、root 或免密 sudo。使用官方稳定版安装器，不加入 Cloud，关闭遥测和自动更新。每 5 秒采集；时间与容量先到者触发清理，容量是软限制。已有安装会直接跳过。</p><button type="submit">预览安装</button></form><pre data-plan hidden></pre><button data-confirm hidden>确认安装到此机器</button></details><pre data-status role="status"></pre>`;
  document.body.append(dialog);const $=s=>dialog.querySelector(s),form=$('[data-connect]'),install=$('[data-install]'),status=$('[data-status]');let editId=null,historyId=null,plan=null,busy=false,instances=[],charts=[];
  const api=(action,payload={})=>invoke('machines_api',{action,payload});
  async function run(work){if(busy)return;busy=true;dialog.querySelectorAll('button:not([data-dismiss])').forEach(b=>b.disabled=true);try{await work();}catch(e){status.textContent=String(e);}finally{busy=false;dialog.querySelectorAll('button').forEach(b=>b.disabled=false);}}
  function option(value,label){const el=document.createElement('option');el.value=value;el.textContent=label;return el;}
  function setCharts(list){charts=list;const old=form.elements.network.value;form.elements.network.replaceChildren(option('system.net','所有物理网卡 · system.net'));for(const c of list.filter(c=>c.id.startsWith('net.')))form.elements.network.append(option(c.id,c.id));if([...form.elements.network.options].some(o=>o.value===old))form.elements.network.value=old;$('[data-chart]').replaceChildren(...list.map(c=>option(c.id,`${c.id} · ${c.units||''}`)));if(list.some(c=>c.id==='system.cpu'))$('[data-chart]').value='system.cpu';}
  async function refresh(){const data=await api('state');instances=data.config.netdata||[];const root=$('[data-instances]');root.replaceChildren();for(const instance of instances){const row=document.createElement('div');row.className='netdata-instance';const text=document.createElement('span');text.textContent=instance.name;const edit=document.createElement('button');edit.textContent='编辑';edit.onclick=()=>{editId=instance.id;form.elements.name.value=instance.name;form.elements.url.value=instance.url;setCharts([]);if(instance.networkChart&&instance.networkChart!=='system.net')form.elements.network.append(option(instance.networkChart,instance.networkChart));form.elements.network.value=instance.networkChart||'system.net';};const history=document.createElement('button');history.textContent='历史曲线';history.onclick=()=>run(async()=>{status.textContent='读取指标…';const result=await api('netdataTest',instance);setCharts(result.charts);historyId=instance.id;$('[data-history]').hidden=false;await query();});const remove=document.createElement('button');remove.textContent='移除接入';remove.onclick=()=>run(async()=>{await api('netdataRemove',{id:instance.id});await refresh();if(historyId===instance.id){historyId=null;$('[data-history]').hidden=true;}status.textContent='已移除接入，远端 Agent 未更改';});row.append(text,edit,history,remove);root.append(row);}install.elements.host.replaceChildren();for(const h of (data.config.hosts||[]).filter(h=>!h.bastion&&!h.readOnly))install.elements.host.append(option(h.id,h.name+' · '+h.alias));}
  button.onclick=()=>{dialog.showModal();status.textContent=invoke?'':'请在 FlowHub 中配置；浏览器预览不会连接或安装。';if(invoke)run(refresh);};$('[data-dismiss]').onclick=()=>dialog.close();
  const instance=()=>({id:editId||crypto.randomUUID(),name:form.elements.name.value.trim(),url:form.elements.url.value.trim(),networkChart:form.elements.network.value});
  $('[data-reset]').onclick=()=>{editId=null;form.reset();setCharts([]);};
  $('[data-test]').onclick=()=>{if(!invoke||!form.reportValidity())return;run(async()=>{status.textContent='正在连接…';const data=await api('netdataTest',instance());setCharts(data.charts);status.textContent=`连接成功，发现 ${data.charts.length} 项指标，可选择具体网卡。`;});};
  form.onsubmit=e=>{e.preventDefault();if(!invoke)return;run(async()=>{await api('netdataSave',instance());editId=null;form.reset();await refresh();status.textContent='已保存，下一次刷新后可添加到桌面组件。';});};
  async function query(){if(!historyId)return;const chart=$('[data-chart]').value;status.textContent='正在读取历史…';const data=await api('netdataHistory',{id:historyId,chart,seconds:Number($('[data-range]').value)});draw(data,charts.find(c=>c.id===chart)?.units||'');status.textContent='历史数据读取完成';}
  $('[data-query]').onclick=()=>run(query);
  function draw(data,units){const root=$('[data-graph]');root.replaceChildren();const rows=(data.data||[]).filter(r=>Array.isArray(r)&&Number.isFinite(r[0])).sort((a,b)=>a[0]-b[0]);if(!rows.length){root.textContent='此时间范围没有数据';return;}const colors=['#b0d8bd','#efa85d','#7baed7','#d995af','#b4a0dc','#e6d67f'];const values=rows.flatMap(r=>r.slice(1)).filter(Number.isFinite),min=Math.min(0,...values),max=Math.max(1,...values),start=rows[0][0],end=rows.at(-1)[0];const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 700 230');svg.setAttribute('role','img');svg.setAttribute('aria-label',`历史指标曲线，单位 ${units}`);svg.classList.add('netdata-graph');const legend=document.createElement('div');legend.className='netdata-legend';data.labels.slice(1).forEach((name,i)=>{let d='',pen=false;for(const r of rows){const v=r[i+1];if(!Number.isFinite(v)){pen=false;continue;}const x=40+(r[0]-start)/(end-start||1)*640,y=190-(v-min)/(max-min||1)*170;d+=`${pen?'L':'M'}${x.toFixed(1)},${y.toFixed(1)} `;pen=true;}const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',d);path.setAttribute('stroke',colors[i%colors.length]);path.setAttribute('fill','none');path.setAttribute('stroke-width','1.6');svg.append(path);const item=document.createElement('span');item.className='netdata-series';const dot=document.createElement('i');dot.style.background=colors[i%colors.length];item.append(dot,document.createTextNode(String(name)));legend.append(item);});for(const [x,y,text] of [[5,18,`${max.toFixed(1)} ${units}`],[5,192,min.toFixed(1)],[40,220,new Date(start*1000).toLocaleString()],[470,220,new Date(end*1000).toLocaleString()]]){const el=document.createElementNS(svg.namespaceURI,'text');el.setAttribute('x',x);el.setAttribute('y',y);el.setAttribute('fill','#afc4b8');el.setAttribute('font-size','10');el.textContent=text;svg.append(el);}root.append(svg,legend);}
  install.oninput=()=>{plan=null;$('[data-confirm]').hidden=true;$('[data-plan]').hidden=true;};
  install.onsubmit=e=>{e.preventDefault();if(!invoke)return;run(async()=>{const payload={hostId:install.elements.host.value,port:Number(install.elements.port.value),bind:install.elements.bind.value,days:Number(install.elements.days.value),disk:Number(install.elements.disk.value)};const result=await api('netdataInstallPlan',payload);plan={...payload,...result,expectedAlias:result.alias};$('[data-plan]').textContent=`目标：${result.name} (${result.alias})\n\n${result.command}`;$('[data-plan]').hidden=false;$('[data-confirm]').hidden=false;});};
  $('[data-confirm]').onclick=()=>{if(!plan)return;run(async()=>{const result=await api('netdataInstall',plan);plan=null;$('[data-confirm]').hidden=true;status.textContent='安装任务已提交，可关闭窗口，结果保存在执行记录中。';let missing=0;for(let i=0;i<310;i++){await new Promise(r=>setTimeout(r,2000));let job;try{job=await api('job',{id:result.id});}catch(e){if(++missing>5)throw e;continue;}status.textContent=`安装任务：${job.status}\n${job.stdout||''}\n${job.stderr||''}`;if(job.finishedAt)return;}status.textContent+='\n请在执行记录中查看最终状态。';});};
})();
