import {mkdirSync,copyFileSync,chmodSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
mkdirSync('bin',{recursive:true});
execFileSync('npm',['run','typecheck'],{stdio:'inherit'});
execFileSync('cargo',['build','--manifest-path','backend/Cargo.toml','--release'],{stdio:'inherit'});
copyFileSync('backend/target/release/flowhub-twofa','bin/flowhub-twofa');
chmodSync('bin/flowhub-twofa',0o700);
execFileSync(process.execPath,[fileURLToPath(new URL('../../../scripts/package-plugin.mjs',import.meta.url)),'twofa'],{stdio:'inherit'});
execFileSync('npm',['run','build:ui'],{stdio:'inherit'});
execFileSync(process.execPath,['scripts/check-build.mjs'],{stdio:'inherit'});
