(() => {
  const invoke=window.FlowHubPlugin?.invoke||window.__TAURI__?.core?.invoke;
  const dialog=document.createElement('dialog');dialog.className='netdata-dialog';dialog.innerHTML=`<div class="section-head"><h2>Netdata 监控</h2><button type="button" data-dismiss>关闭</button></div>
  <p class="netdata-note">每台机器连接自己的 Agent，历史数据保留在远端，关闭 FlowHub 后仍继续采集。</p><div data-instances></div>
  <form data-connect><h3>接入已有 Netdata</h3><p class="netdata-note">填 Agent 的 HTTP 地址，不是 SSH 地址：FlowHub 直接连 Agent 的 19999 端口取指标。地址用 <code>http://机器IP:19999</code>，并确保 Agent 监听所有网卡、机器防火墙与云安全组放行了该端口。</p><p class="netdata-note" data-agent-suggestion hidden role="status"></p><div class="netdata-fields"><label>机器名称<input name="name" required maxlength="40" placeholder="生产服务器"></label><label>Agent 地址<input name="url" required type="url" placeholder="http://机器IP:19999"></label></div><label>网速指标<select name="network"><option value="system.net">所有物理网卡 · system.net</option></select></label><div class="actions"><button type="button" data-use-agent hidden>使用探测到的地址</button><button type="button" data-test>测试并发现指标</button><button type="submit">保存节点</button><button type="button" data-reset>清空</button></div></form>
  <section data-history hidden><h3>历史趋势</h3><div class="netdata-fields"><label>指标<select data-chart></select></label><label>时间范围<select data-range><option value="3600">最近 1 小时</option><option value="86400" selected>最近 1 天</option><option value="604800">最近 7 天</option><option value="2592000">最近 30 天</option></select></label></div><button data-query>查看曲线</button><div data-graph></div><p class="netdata-note">显示 Agent 实际保存的数据；缺失的历史不会补造。</p></section>
  <details><summary>在机器上安装 Netdata</summary><form data-install><label>目标机器<select name="host" required></select></label><div class="netdata-fields"><label>端口<input name="port" type="number" min="1024" max="65535" value="19999" required></label><label>监听范围<select name="bind"><option value="0.0.0.0">所有网卡 · 用 IP 直连（推荐）</option><option value="127.0.0.1">仅本机 · 需自行建立隧道</option></select></label><label>历史保留<select name="days"><option value="7">7 天</option><option value="30">30 天</option><option value="90">90 天</option></select></label><label>指标存储目标容量<select name="disk"><option value="512">512 MiB</option><option value="1024" selected>1 GiB</option><option value="2048">2 GiB</option><option value="4096">4 GiB</option></select></label></div><p class="netdata-note">需要 Linux、curl、root 或免密 sudo。使用官方稳定版安装器，不加入 Cloud，关闭遥测和自动更新。每 5 秒采集；时间与容量先到者触发清理，容量是软限制。已有安装会直接跳过。</p><button type="submit">预览安装</button></form><pre data-plan hidden></pre><button data-confirm hidden>确认安装到此机器</button></details><pre data-status role="status"></pre>`;
  document.body.append(dialog);const $=s=>dialog.querySelector(s),form=$('[data-connect]'),install=$('[data-install]'),status=$('[data-status]');let editId=null,historyId=null,plan=null,busy=false,instances=[],charts=[];
  const api=(action,payload={})=>invoke('machines_api',{action,payload});
  async function run(work){if(busy)return;busy=true;dialog.querySelectorAll('button:not([data-dismiss])').forEach(b=>b.disabled=true);try{await work();}catch(e){status.textContent=String(e);}finally{busy=false;dialog.querySelectorAll('button').forEach(b=>b.disabled=false);}}
  function option(value,label){const el=document.createElement('option');el.value=value;el.textContent=label;return el;}
  function setCharts(list){charts=list;const old=form.elements.network.value;form.elements.network.replaceChildren(option('system.net','所有物理网卡 · system.net'));for(const c of list.filter(c=>c.id.startsWith('net.')))form.elements.network.append(option(c.id,c.id));if([...form.elements.network.options].some(o=>o.value===old))form.elements.network.value=old;$('[data-chart]').replaceChildren(...list.map(c=>option(c.id,`${c.id} · ${c.units||''}`)));if(list.some(c=>c.id==='system.cpu'))$('[data-chart]').value='system.cpu';}
  async function refresh(){const data=await api('state');instances=data.config.netdata||[];const root=$('[data-instances]');root.replaceChildren();for(const instance of instances){const row=document.createElement('div');row.className='netdata-instance';const text=document.createElement('span');text.textContent=instance.name;const edit=document.createElement('button');edit.textContent='编辑';edit.onclick=()=>{editId=instance.id;form.elements.name.value=instance.name;form.elements.url.value=instance.url;setCharts([]);if(instance.networkChart&&instance.networkChart!=='system.net')form.elements.network.append(option(instance.networkChart,instance.networkChart));form.elements.network.value=instance.networkChart||'system.net';};const history=document.createElement('button');history.textContent='历史曲线';history.onclick=()=>run(async()=>{status.textContent='读取指标…';const result=await api('netdataTest',instance);setCharts(result.charts);historyId=instance.id;$('[data-history]').hidden=false;await query();});const remove=document.createElement('button');remove.textContent='移除接入';remove.onclick=()=>run(async()=>{await api('netdataRemove',{id:instance.id});await refresh();if(historyId===instance.id){historyId=null;$('[data-history]').hidden=true;}status.textContent='已移除接入，远端 Agent 未更改';});row.append(text,edit,history,remove);root.append(row);}install.elements.host.replaceChildren();for(const h of (data.config.hosts||[]).filter(h=>!h.bastion&&!h.readOnly))install.elements.host.append(option(h.id,h.name+' · '+h.alias));}
  async function open(hostId,hostName){
   dialog.showModal();status.textContent=invoke?'':'请在 FlowHub 中配置；浏览器预览不会连接或安装。';
   if(!invoke)return;
   await run(async()=>{await refresh();if(hostName)form.elements.name.value=hostName;
    if(hostId&&[...install.elements.host.options].some(o=>o.value===hostId))install.elements.host.value=hostId;});
  }
  window.FlowHubNetdata={open};
  const instance=()=>({id:editId||crypto.randomUUID(),name:form.elements.name.value.trim(),url:form.elements.url.value.trim(),networkChart:form.elements.network.value});
  $('[data-dismiss]').onclick=()=>dialog.close();
  $('[data-reset]').onclick=()=>{editId=null;form.reset();setCharts([]);};
  $('[data-test]').onclick=()=>{if(!invoke||!form.reportValidity())return;run(async()=>{status.textContent='正在连接…';const data=await api('netdataTest',instance());setCharts(data.charts);status.textContent=`连接成功，发现 ${data.charts.length} 项指标，可选择具体网卡。`;});};
  form.onsubmit=e=>{e.preventDefault();if(!invoke)return;run(async()=>{await api('netdataSave',instance());editId=null;form.reset();await refresh();status.textContent='已保存，下一次刷新后可添加到桌面组件。';});};
  async function query(){if(!historyId)return;const chart=$('[data-chart]').value;status.textContent='正在读取历史…';const data=await api('netdataHistory',{id:historyId,chart,seconds:Number($('[data-range]').value)});draw(data,charts.find(c=>c.id===chart)?.units||'');status.textContent='历史数据读取完成';}
  $('[data-query]').onclick=()=>run(query);
  function draw(data,units){const root=$('[data-graph]');root.replaceChildren();const rows=(data.data||[]).filter(r=>Array.isArray(r)&&Number.isFinite(r[0])).sort((a,b)=>a[0]-b[0]);if(!rows.length){root.textContent='此时间范围没有数据';return;}const colors=['#b0d8bd','#efa85d','#7baed7','#d995af','#b4a0dc','#e6d67f'];const values=rows.flatMap(r=>r.slice(1)).filter(Number.isFinite),min=Math.min(0,...values),max=Math.max(1,...values),start=rows[0][0],end=rows.at(-1)[0];const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 700 230');svg.setAttribute('role','img');svg.setAttribute('aria-label',`历史指标曲线，单位 ${units}`);svg.classList.add('netdata-graph');const legend=document.createElement('div');legend.className='netdata-legend';data.labels.slice(1).forEach((name,i)=>{let d='',pen=false;for(const r of rows){const v=r[i+1];if(!Number.isFinite(v)){pen=false;continue;}const x=40+(r[0]-start)/(end-start||1)*640,y=190-(v-min)/(max-min||1)*170;d+=`${pen?'L':'M'}${x.toFixed(1)},${y.toFixed(1)} `;pen=true;}const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',d);path.setAttribute('stroke',colors[i%colors.length]);path.setAttribute('fill','none');path.setAttribute('stroke-width','1.6');svg.append(path);const item=document.createElement('span');item.className='netdata-series';const dot=document.createElement('i');dot.style.background=colors[i%colors.length];item.append(dot,document.createTextNode(String(name)));legend.append(item);});for(const [x,y,text] of [[5,18,`${max.toFixed(1)} ${units}`],[5,192,min.toFixed(1)],[40,220,new Date(start*1000).toLocaleString()],[470,220,new Date(end*1000).toLocaleString()]]){const el=document.createElementNS(svg.namespaceURI,'text');el.setAttribute('x',x);el.setAttribute('y',y);el.setAttribute('fill','#afc4b8');el.setAttribute('font-size','10');el.textContent=text;svg.append(el);}root.append(svg,legend);}
  // 注意：这里是唯一的 install.oninput 处理器。再写一行会覆盖它，导致 plan 无法失效、确认按钮状态错乱。
  install.oninput=()=>{plan=null;$('[data-confirm]').hidden=true;$('[data-plan]').hidden=true;$('[data-agent-suggestion]').hidden=true;$('[data-use-agent]').hidden=true;};
  install.onsubmit=e=>{e.preventDefault();if(!invoke)return;run(async()=>{const payload={hostId:install.elements.host.value,port:Number(install.elements.port.value),bind:install.elements.bind.value,days:Number(install.elements.days.value),disk:Number(install.elements.disk.value)};const result=await api('netdataInstallPlan',payload);plan={...payload,...result,expectedAlias:result.alias};$('[data-plan]').textContent=`目标：${result.name} (${result.alias})\n\n${result.command}`;$('[data-plan]').hidden=false;$('[data-confirm]').hidden=false;});};
  $('[data-confirm]').onclick=()=>{if(!plan)return;run(async()=>{const result=await api('netdataInstall',plan);plan=null;$('[data-confirm]').hidden=true;const started=Date.now();const uiWaitSeconds=120;const elapsed=()=>{const s=Math.round((Date.now()-started)/1000);return `${Math.floor(s/60)} 分 ${String(s%60).padStart(2,'0')} 秒`;};status.textContent='安装任务已提交，可关闭窗口，结果保存在执行记录中。';for(let i=0;i<uiWaitSeconds/2;i++){await new Promise(r=>setTimeout(r,2000));let job=null;try{job=await api('job',{id:result.id});}catch(e){
   // 后端在任务运行期间可能暂时查不到记录（历史只在结束后写入）。这属于正常的等待，
   // 不能当成失败：之前连续 6 次就 throw，用户在任务正常执行时就看到「记录已过期或任务未结束」。
   // 只有明确表示任务不存在且已等待很久时，才提示去执行记录里查看。
   status.textContent=`安装任务执行中…已等待 ${elapsed()}\n（任务在服务器上继续执行，关闭本窗口不会中断）`;continue;}
  if(!job){status.textContent=`安装任务执行中…已等待 ${elapsed()}\n（任务在服务器上继续执行，关闭本窗口不会中断）`;continue;}
  status.textContent=`安装任务：${job.status}（已等待 ${elapsed()}）\n${job.stdout||''}\n${job.stderr||''}`;
  if(job.finishedAt){offerDiscoveredAgent(job);return;}}
  status.textContent=`前端已等待 ${elapsed()}，停止占用此窗口。后台安装任务仍在服务器上继续，完成后请到执行记录查看最终状态。`;});};
  // 安装脚本结束时回传探测到的地址（FLOWHUB_NETDATA_AGENT_HOST/PORT），这里解析出来直接填进接入表单，
  // 免得用户自己去拼 http://IP:19999。云主机 NAT 下探测到的可能是内网地址，所以仍然让用户确认后再保存。
  function offerDiscoveredAgent(job){if(!job||job.status!=='success')return;const text=`${job.stdout||''}\n${job.stderr||''}`;const host=/FLOWHUB_NETDATA_AGENT_HOST=(\S*)/.exec(text)?.[1]?.trim();const port=/FLOWHUB_NETDATA_AGENT_PORT=(\d+)/.exec(text)?.[1];const hint=$('[data-agent-suggestion]'),use=$('[data-use-agent]');
  // 回传了端口但地址为空：只有「机器自己也不知道自己的 IP」这一种情况（无外网、无默认路由）。
  // 这时给出明确的拼装方式，而不是静默结束。
  if(port&&!host){hint.hidden=false;hint.textContent=`未能自动探测到机器 IP（Agent 端口 ${port}）。请在 Agent 地址里填写 http://<机器IP>:${port}，并确认 Agent 已监听所有网卡、防火墙与云安全组已放行。`;return;}
  // 兜底：IPv6 不带方括号时 http://2402:...:19999 是非法 URL（端口与末段 hextet 混淆），
  // 后端已保证补括号，这里再挡一次，避免把用不了的地址填进表单。
  const normalized=host.includes(':')&&!host.startsWith('[')?`[${host}]`:host;
  if(!host||!port)return;const url=`http://${normalized}:${port}`;
  // 安装任务回传的地址就是本次目标机器的 Agent 地址，直接回填；仍要求用户
  // 点击「测试并发现指标」确认 FlowHub 到 Agent 的网络路径后再保存。
  form.elements.url.value=url;
  if(!form.elements.name.value.trim()){const selected=install.elements.host.selectedOptions[0]?.textContent||'';form.elements.name.value=selected.split(' · ')[0].trim();}
  hint.hidden=false;hint.textContent=`已自动填入 Agent 地址 ${url}，请点「测试并发现指标」验证后保存。`;use.hidden=true;}
})();
